### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by thegodone** [elucideye/xgboostcpp#1]
I have a mac, how to compile ?

**Comment by headupinclouds** [comment]
I'll update the instructions this weekend and add cross platform Travis and Appveyor CI tests.  For now you can follow the README on this project 

https://github.com/forexample/hunter-simple

Once you download and install polly, you can run a build command like this:

```
polly.py --toolchain libcxx --verbose --install
```

This should work on Mac OS as is in the current project state.  I will make boost serialization optional to avoid the additional build time (cereal works well and is lightweight).

**Comment by headupinclouds** [comment]
The main project README has been updated with build instructions.  I've also added cross platform Travis and Appveyor build support which can be used as a reference if needed + a high level regression problem unit test.  Closing...

**Comment by thegodone** [comment]
thanks
