### ISSUE TITLE
How to use cpp in Matlab ?

### ISSUE THREAD

**Issue by thegodone** [elucideye/xgboostcpp#2]
I want to write a wrapper from cpp to matlab
Do I need the HunterGate dependancies ?

**Comment by headupinclouds** [comment]
I think it is better to discuss adding a Matlab interface directly in the xgboost repository (I don't believe any dependencies will be required).  I plan to update the xgboost version in hunter and provide an option for building without dependencies, but won't have time for it in the near future.  This was initially posted as a sample of the C++ API (by request) based on some code I had in another project.  SWIG is one framework I've seen that helps with multi-language API wrappers:

https://www.mathworks.com/matlabcentral/newsreader/view_thread/8451
